---
title: "About"
---

<br>

# Analysis

This website will show updated analyses COVID19 analyses. It is currently updated with data as of Oct 15, 2020. The content currently shown corresponds to the paper [**Risk-stratified COVID-19 policy analysis for Los Angeles County through an integrated risk and stochastic epidemiological model**](https://github.com/AbigailHorn/COV2-LA). The co-authors of this paper and members of this team are shown below.

<br>

# Team

## USC Department of Preventive Medicine

[Abigail Horn, PhD](http://abigail-horn.com/)
Postdoctoral Research Fellow, Center for Applied Network Analysis, 
Department of Preventive Medicine

[Lai Jiang, MS](https://scholar.google.com/citations?user=GhsMHqYAAAAJ&hl=en)
Biostatistics PhD Candidate

[Emil Hvitfeldt, MS](https://www.hvitfeldt.me/)
Research Programmer

## USC Department of Preventive Medicine

[Abigail Horn, PhD](http://abigail-horn.com/)
Postdoctoral Research Fellow, Center for Applied Network Analysis, 
Department of Preventive Medicine

[Lai Jiang, MS](https://scholar.google.com/citations?user=GhsMHqYAAAAJ&hl=en)
Biostatistics PhD Candidate

[Emil Hvitfeldt, MS](https://www.hvitfeldt.me/)
Research Programmer

[Wendy Cozen, DO, MPH](https://keck.usc.edu/faculty-search/wendy-cozen/)
Professor of Preventive Medicine
Leader, Translational Epidemiology
Director, Population-based Tissue Procurement Core

[Kayla de la Haye](https://www.kayladelahaye.net/)
Assistant Professor of Preventive Medicine

[David Conti, PhD](https://keck.usc.edu/faculty-search/david-v-conti/)
Professor of Preventive Medicine
Associate Director for Data Science Integration

## USC Sol Price School of Public Policy

[Neeraj Sood](https://priceschool.usc.edu/people/neeraj-sood/)

Professor, Vice Dean for Faculty Affairs, Vice Dean for Research
USC Sol Price School of Public Policy
USC USC Schaeffer Center for Health Policy

## Los Angeles County Department of Public Health (LACDPH)

[Paul Simon, MD, MPH](https://ph.ucla.edu/faculty/simon), 
Chief Science Officer and Director of the Division of Assessment, Planning, and Quality, LACDPH
Adjunct Professor, Department of Epidemiology, UCLA Fielding School of Public Health

[Will Nicholas, PhD, MPH](http://publichealth.lacounty.gov/chie/who_we_are_2.htm)
Director, Center for Health Impact Evaluation, LACDPH

[Faith Washburn, MPH](http://publichealth.lacounty.gov/chie/who_we_are_2.htm)
Epidemiology Analyst

