
###############################################################################################################
## CALCULATE RISK PROBABILITIES
###############################################################################################################


###############################################################################################################
### Read in calculated risk profiles (JAM model estimates) and marginal population prevalences

### Read in risk profiles and probaiblities generated by JAM
Pr.H.readin = read.table(path(data.dir, "Ordinal.Obesity.DummyRiskProfile.Hospitalization.txt"), sep=" ", header=TRUE )
Pr.Q.readin = read.table(path(data.dir, "Ordinal.Obesity.DummyRiskProfile.ICU.txt"), sep=" ", header=TRUE )
Pr.D.readin = read.table(path(data.dir, "Ordinal.Obesity.DummyRiskProfile.Death.txt"), sep=" ", header=TRUE )

### Add the 3 weight statuses
add.probs.mat <- function(Probs.mat){
  ## Copy first row
  first.row <- Probs.mat[1,]
  n <- 2
  replicated <- do.call("rbind", replicate(n, first.row, simplify=FALSE))
  Probs.mat <- rbind(replicated, Probs.mat)

  ## Add weight status
  Probs.mat$ObesityBMI.30[1] = 1
  Probs.mat$ObesityBMI30.40[2] = 1
  Probs.mat$ObesityBMI.40[3] = 1

  return(Probs.mat)
}
Pr.H <- add.probs.mat(Pr.H.readin)
Pr.Q <- add.probs.mat(Pr.Q.readin)
Pr.D <- add.probs.mat(Pr.D.readin)

#########################################################################################################
### POPULATION RISK FACTOR PREVALENCE FOR LA COUNTY
### Data coming from [Los Angeles County Health Survey](http://www.publichealth.lacounty.gov/ha/hasurveyintro.htm)

Pop.prevalence.race = read.csv(path(data.dir, "Pop.prevalence.BMI.csv"), sep=",", header=TRUE,row.names = 1 )
Pop.prevalence <- Pop.prevalence.race
Pop.prev.matrix<-as.matrix(Pop.prevalence)

SIGMA.BMI = read.csv(path(data.dir, "Each.Comb.Corr.Weighted.txt"), sep=" ", header=TRUE,row.names = 1)
SIGMA2 <- select(SIGMA.BMI, -c(stroke,hepB,kidney))
SIGMA2 <- SIGMA2[-c(13,14,16),]
colnames(SIGMA2) <- colnames(Pop.prevalence)
rownames(SIGMA2) <- colnames(Pop.prevalence)

### Keep track of which index corresponds to which SPA
SPA.order <- rownames(Pop.prevalence)


#########################################################################################################
#########################################################################################################
## **FILTERING** TO GET GROUP-AVERAGED PROBABILITIES OF SEVERE ILLNESS


#########################################################################################################
### Calculate weighted average Pr(H) Pr(Q) Pr(D) for each region

## FULL POPULATION
Pr.H.filter <- Pr.H
Pr.Q.filter <- Pr.Q
Pr.D.filter <- Pr.D

## FILTERED POPULATION
# Pr.H.filter <- filter(Pr.H, Age65.==0 & ComorbidityYes==0)
# Pr.Q.filter <- filter(Pr.Q, Age65.==0 & ComorbidityYes==0)
# Pr.D.filter <- filter(Pr.D, Age65.==0 & ComorbidityYes==0)

# Pr.H.filter <- filter(Pr.H, Age45.64==1 | Age20.44==1)
# Pr.Q.filter <- filter(Pr.Q, Age45.64==1 | Age20.44==1)
# Pr.D.filter <- filter(Pr.D, Age45.64==1 | Age20.44==1)

## FILTER INDEPENDENT
profile.cnt.SPAs <- matrix(0, nrow = nrow(Pr.H.filter), ncol = nrow(Pop.prevalence))
H.profile.share.relative.all.SPAs <- matrix(0, nrow = nrow(Pr.H.filter), ncol = nrow(Pop.prevalence))
Q.profile.share.relative.all.SPAs <- matrix(0, nrow = nrow(Pr.H.filter), ncol = nrow(Pop.prevalence))
D.profile.share.relative.all.SPAs <- matrix(0, nrow = nrow(Pr.H.filter), ncol = nrow(Pop.prevalence))
H.risk.all.SPAs <- c(rep(0,nrow(Pop.prevalence)))
Q.risk.all.SPAs <- c(rep(0,nrow(Pop.prevalence)))
D.risk.all.SPAs <- c(rep(0,nrow(Pop.prevalence)))

remove.50 = FALSE # TRUE
percentage.to.remove = 1

for (idx in 1:nrow(Pop.prevalence)) {

  margprob.SPA <- Pop.prev.matrix[idx,]
  sample.pop.SPA <- rmvbin(10000, margprob=margprob.SPA, sigma=SIGMA2)
  sample.pop.df <- as.data.frame(sample.pop.SPA)
  colnames(sample.pop.df)<-colnames(Pop.prev.matrix)

  ### Create an "any comorbidity" vector
  any.comb <- c(rep(0,nrow(sample.pop.SPA)))

  for (i in 1:nrow(sample.pop.df)) {
    if(sample.pop.df$diabetes[i]==1 || sample.pop.df$hypertension[i]==1 || sample.pop.df$copd[i]==1 || sample.pop.df$coronary[i]==1 || sample.pop.df$cancer[i]==1)
    {any.comb[i]=1}
  }

  ### Create a new sample.pop df with the individual comborbidities deleted and the "any.comb" added
  sample.pop.df <- sample.pop.df %>% dplyr::select(-c(diabetes,hypertension,copd,coronary,cancer))
  sample.pop.df$any.comb <- any.comb

  ### Count population prevalence of profiles (much faster with as.matrix())
  profiles <- as.matrix(dplyr::select(Pr.H.filter, -1))
  sample.pop.table <- as.matrix(sample.pop.df)

  profile.cnt <- c(rep(0,dim(profiles)[1]))
  for (i in 1:dim(profiles)[1]) {
    for (j in 1:dim(sample.pop.table)[1]) {
      if(all(profiles[i,]==sample.pop.table[j,]))
      {profile.cnt[i]<-(profile.cnt[i]+1)}
    }
  }

  ####################################################
  ## FOR REMOVING 50% OF ELDERLY
  ####################################################
  # if (remove.50==TRUE){
  #   profile.cnt.reduce <- profile.cnt
  #   for (k in 1:length(profile.cnt)){
  #     if (profiles[k,"Age65."]==1){
  #       profile.cnt.reduce[k] = profile.cnt.reduce[k]*percentage.to.remove
  #     }
  #   }
  #
  #   profile.cnt <- profile.cnt.reduce
  # }
  ####################################################
  ####################################################

  ### Get frequency distribution of profiles
  profile.cnt.freq <- profile.cnt/sum(profile.cnt)
  profile.cnt.SPAs[,idx]<-profile.cnt.freq
  print(idx)
  print(round(profile.cnt.freq,digits=3))

  ### Calculate weighted average risk probability for the SPA across all profiles:
  ### H given general population, Q given H population, D given Q population

  # Profile prevalence within general population:
  pop.profile.share.relative <- profile.cnt.freq

  # Weighted avg for Pr(H): Profile prevalence within general population * Profile specific Pr(H)
  H.profile.share <- pop.profile.share.relative*t(dplyr::select(Pr.H.filter,1))
  H.risk.weighted.avg <- sum(H.profile.share)

  # Profile prevalence with hospitalized population
  H.profile.share.relative <- H.profile.share/(H.risk.weighted.avg)

  print(round(H.profile.share.relative,digits=3))

  # Weighted avg for Pr(Q): Profile prevalence within hospitalized population * Profile specific Pr(Q)
  Q.profile.share <- H.profile.share.relative*t(dplyr::select(Pr.Q.filter,1))
  Q.risk.weighted.avg <- sum(Q.profile.share)

  # Profile prevalence within ICU population
  Q.profile.share.relative <- Q.profile.share/(Q.risk.weighted.avg)

  # Weighted avg for Pr(D): Profile prevalence within ICU population * Profile specific Pr(D)
  D.profile.share <- Q.profile.share.relative*t(dplyr::select(Pr.D.filter,1))
  D.risk.weighted.avg <- sum(D.profile.share)

  # Profile prevalence within dead population (used later)
  D.profile.share.relative <- D.profile.share/(D.risk.weighted.avg)

  ### Save the weighted risk probabilities in a vector
  H.risk.all.SPAs[idx] = H.risk.weighted.avg
  Q.risk.all.SPAs[idx] = Q.risk.weighted.avg
  D.risk.all.SPAs[idx] = D.risk.weighted.avg

  ### Save the relative share of each profile in a matrix
  H.profile.share.relative.all.SPAs[,idx] <- H.profile.share.relative
  Q.profile.share.relative.all.SPAs[,idx] <- Q.profile.share.relative
  D.profile.share.relative.all.SPAs[,idx] <- D.profile.share.relative

}

### For displaying the population prevalence by SPA and LA County
### NOTE: THIS TABLE profile.cnt.SPAs IS WHAT IS USED IN THE data.prev TABLE (it is read in as "data" and merged with other tables)
colnames(profile.cnt.SPAs) = SPA.order
profile.cnt.SPAs<-round(profile.cnt.SPAs,digits=5)

profile.cnt.SPAs<-cbind(profile.cnt.SPAs,profiles)
kable(profile.cnt.SPAs) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

colnames(H.profile.share.relative.all.SPAs) = SPA.order
H.profile.share.relative.all.SPAs <- cbind(H.profile.share.relative.all.SPAs,profiles)

colnames(Q.profile.share.relative.all.SPAs) = SPA.order
Q.profile.share.relative.all.SPAs <- cbind(Q.profile.share.relative.all.SPAs,profiles)

colnames(D.profile.share.relative.all.SPAs) = SPA.order
D.profile.share.relative.all.SPAs <- cbind(D.profile.share.relative.all.SPAs,profiles)

# write.csv(profile.cnt.SPAs, file = path(result.dir, "ProfilePrev.GeneralPop.csv"))
# write.csv(H.profile.share.relative.all.SPAs, file = path(result.dir, "ProfilePrev.HospitalPop.csv"))
# write.csv(Q.profile.share.relative.all.SPAs, file = path(result.dir, "ProfilePrev.ICUPop.csv"))
# write.csv(D.profile.share.relative.all.SPAs, file = path(result.dir, "ProfilePrev.DeadPop.csv"))


#########################################################################################################
### CALCULATED RISK PROBABILITIES
### Probability of hospitalization = Pr(H)
### Probability of ICU, given hospitalization = Pr(Q)
### Probability of death, given ICU = Pr(D)

### Dataframe with risk probabilities
risk.probs.SPAs <-
  data.frame(H.risk.all.SPAs,Q.risk.all.SPAs,D.risk.all.SPAs) %>%
  mutate(H.risk.all.SPAs = round(H.risk.all.SPAs,3),
         Q.risk.all.SPAs = round(Q.risk.all.SPAs,3),
         D.risk.all.SPAs = round(D.risk.all.SPAs,3))

rownames(risk.probs.SPAs) <- SPA.order
names(risk.probs.SPAs) <- c("Pr(Hospital|Illness)","Pr(ICU|Hosptial)","Pr(Death|ICU)")

risk.probs.LAC.filter <- risk.probs.SPAs[9,]

Alpha.filter.prior.mean <- risk.probs.SPAs[9,1]
Kappa.filter.prior.mean <- risk.probs.SPAs[9,2]
Delta.filter.prior.mean <- risk.probs.SPAs[9,3]


