

###############################################################################################################
## CALCULATE RISK PROBABILITIES
## UPDATING PR(Q) WITH POP PREVALENCE OF PR(H)
## ADDING OBESITY
###############################################################################################################


###############################################################################################################
### Read in calculated risk profiles (JAM model estimates) and marginal population prevalences

#data.dir="/Users/abigailhorn/Dropbox/0 2019/COVID-19/LACounty_modeling/data/corrmats/Ordinal.Age.Binary.Comb_2020_04_03/"
#marginalRR <- read.table(path(data.dir, "Ordinal.Comb.marginE.input.txt"), sep=" ", header=TRUE )

#data.dir="/Users/abigailhorn/Dropbox/0 2019/COVID-19/LACounty_modeling/data/corrmats/Ordinal.Age.Binary.Comb_2020_04_09/"
#data.dir = "/Users/abigailhorn/Dropbox/0 2019/COVID-19/LACounty_modeling/data/corrmats/Ordinal.Obesity_2020_04_20/"


### Read in risk profiles and probaiblities generated by JAM
Pr.H.readin = read.table(path(data.dir, "Ordinal.Obesity.DummyRiskProfile.Hospitalization.txt"), sep=" ", header=TRUE )
Pr.Q.readin = read.table(path(data.dir, "Ordinal.Obesity.DummyRiskProfile.ICU.txt"), sep=" ", header=TRUE )
Pr.D.readin = read.table(path(data.dir, "Ordinal.Obesity.DummyRiskProfile.Death.txt"), sep=" ", header=TRUE )

### Add the 3 weight statuses
add.probs.mat <- function(Probs.mat){
  ## Copy first row
  first.row <- Probs.mat[1,]
  n <- 2
  replicated <- do.call("rbind", replicate(n, first.row, simplify=FALSE))
  Probs.mat <- rbind(replicated, Probs.mat)

  ## Add weight status
  Probs.mat$ObesityBMI.30[1] = 1
  Probs.mat$ObesityBMI30.40[2] = 1
  Probs.mat$ObesityBMI.40[3] = 1

  return(Probs.mat)
}
Pr.H <- add.probs.mat(Pr.H.readin)
Pr.Q <- add.probs.mat(Pr.Q.readin)
Pr.D <- add.probs.mat(Pr.D.readin)

### Write output if sharing
write.csv(Pr.H, file = path(result.dir, "Pr.H.BMI.csv"))
write.csv(Pr.Q, file = path(result.dir, "Pr.Q.BMI.csv"))
write.csv(Pr.D, file = path(result.dir, "Pr.D.BMI.csv"))

#########################################################################################################
## KEY RISK PROFILES
#data.dir="/Users/abigailhorn/Dropbox/0 2019/COVID-19/LACounty_modeling/data/corrmats/Ordinal.Age.Binary.Comb_2020_04_03/"
#Pr.D.FULL = read.table(path(data.dir, "Ordinal.Age.RiskProfile.Death.txt"), sep=" ", header=TRUE )

#risk_profiles_FULL <- Pr.D.FULL[,-1]

#########################################################################################################
### POPULATION RISK FACTOR PREVALENCE FOR LA COUNTY
### Data coming from [Los Angeles County Health Survey](http://www.publichealth.lacounty.gov/ha/hasurveyintro.htm)

Pop.prevalence.race = read.csv(path(data.dir, "Pop.prevalence.BMI.csv"), sep=",", header=TRUE,row.names = 1 )
Pop.prevalence <- Pop.prevalence.race
Pop.prev.matrix<-as.matrix(Pop.prevalence)

SIGMA.BMI = read.csv(path(data.dir, "Each.Comb.Corr.Weighted.txt"), sep=" ", header=TRUE,row.names = 1)
SIGMA2 <- select(SIGMA.BMI, -c(stroke,hepB,kidney))
SIGMA2 <- SIGMA2[-c(13,14,16),]
colnames(SIGMA2) <- colnames(Pop.prevalence)
rownames(SIGMA2) <- colnames(Pop.prevalence)

### Keep track of which index corresponds to which SPA
SPA.order <- rownames(Pop.prevalence)

#########################################################################################################
### Calculate weighted average Pr(H) Pr(Q) Pr(D) for each region

# ## Initialize
# Pr.H.65 <- filter(Pr.H, Age65.==0 & ComorbidityYes==0)
# Pr.Q.65 <- filter(Pr.Q, Age65.==0 & ComorbidityYes==0)
# Pr.D.65 <- filter(Pr.D, Age65.==0 & ComorbidityYes==0)
#
# H.risk.all.SPAs <- c(rep(0,nrow(Pop.prevalence)))
# Q.risk.all.SPAs <- c(rep(0,nrow(Pop.prevalence)))
# D.risk.all.SPAs <- c(rep(0,nrow(Pop.prevalence)))
# profile.cnt.SPAs <- matrix(0, nrow = nrow(Pr.H.65), ncol = nrow(Pop.prevalence))
# H.profile.share.relative.all.SPAs <- matrix(0, nrow = nrow(Pr.H.65), ncol = nrow(Pop.prevalence))
# Q.profile.share.relative.all.SPAs <- matrix(0, nrow = nrow(Pr.H.65), ncol = nrow(Pop.prevalence))
# D.profile.share.relative.all.SPAs <- matrix(0, nrow = nrow(Pr.H.65), ncol = nrow(Pop.prevalence))
#
#
# for (idx in 1:nrow(Pop.prevalence)) {
#
#   margprob.SPA <- Pop.prev.matrix[idx,]
#   sample.pop.SPA <- rmvbin(10000, margprob=margprob.SPA, sigma=SIGMA2)
#   sample.pop.df <- as.data.frame(sample.pop.SPA)
#   colnames(sample.pop.df)<-colnames(Pop.prev.matrix)
#
#   ### Create an "any comorbidity" vector
#   any.comb <- c(rep(0,nrow(sample.pop.SPA)))
#
#   for (i in 1:nrow(sample.pop.df)) {
#     if(sample.pop.df$diabetes[i]==1 || sample.pop.df$hypertension[i]==1 || sample.pop.df$copd[i]==1 || sample.pop.df$coronary[i]==1 || sample.pop.df$cancer[i]==1)
#     {any.comb[i]=1}
#   }
#
#   ### Create a new sample.pop df with the individual comborbidities deleted and the "any.comb" added
#   sample.pop.df <- sample.pop.df %>% dplyr::select(-c(diabetes,hypertension,copd,coronary,cancer))
#   sample.pop.df$any.comb <- any.comb
#
#   ### Count population prevalence of profiles (much faster with as.matrix())
#   profiles <- as.matrix(dplyr::select(Pr.H.65, -1))
#   sample.pop.table <- as.matrix(sample.pop.df)
#
#   profile.cnt <- c(rep(0,dim(profiles)[1]))
#   for (i in 1:dim(profiles)[1]) {
#     for (j in 1:dim(sample.pop.table)[1]) {
#       if(all(profiles[i,]==sample.pop.table[j,]))
#       {profile.cnt[i]<-(profile.cnt[i]+1)}
#     }
#   }
#
#   ### Get frequency distribution of profiles
#   profile.cnt.freq <- profile.cnt/sum(profile.cnt)
#   profile.cnt.SPAs[,idx]<-profile.cnt.freq
#   print(idx)
#   print(round(profile.cnt.freq,digits=3))
#
#   ### Calculate weighted average risk probability for the SPA across all profiles:
#   ### H given general population, Q given H population, D given Q population
#
#   # Profile prevalence within general population:
#   pop.profile.share.relative <- profile.cnt.freq
#
#   # Weighted avg for Pr(H): Profile prevalence within general population * Profile specific Pr(H)
#   H.profile.share <- pop.profile.share.relative*t(dplyr::select(Pr.H.65,1))
#   H.risk.weighted.avg <- sum(H.profile.share)
#
#   # Profile prevalence with hospitalized population
#   H.profile.share.relative <- H.profile.share/(H.risk.weighted.avg)
#
#   print(round(H.profile.share.relative,digits=3))
#
#
#   # Weighted avg for Pr(Q): Profile prevalence within hospitalized population * Profile specific Pr(Q)
#   Q.profile.share <- H.profile.share.relative*t(dplyr::select(Pr.Q.65,1))
#   Q.risk.weighted.avg <- sum(Q.profile.share)
#
#   # Profile prevalence within ICU population
#   Q.profile.share.relative <- Q.profile.share/(Q.risk.weighted.avg)
#
#   # Weighted avg for Pr(D): Profile prevalence within ICU population * Profile specific Pr(D)
#   D.profile.share <- Q.profile.share.relative*t(dplyr::select(Pr.D.65,1))
#   D.risk.weighted.avg <- sum(D.profile.share)
#
#   # Profile prevalence within dead population (used later)
#   D.profile.share.relative <- D.profile.share/(D.risk.weighted.avg)
#
#   ### Save the weighted risk probabilities in a vector
#   H.risk.all.SPAs[idx] = H.risk.weighted.avg
#   Q.risk.all.SPAs[idx] = Q.risk.weighted.avg
#   D.risk.all.SPAs[idx] = D.risk.weighted.avg
#
#   ### Save the relative share of each profile in a matrix
#   H.profile.share.relative.all.SPAs[,idx] <- H.profile.share.relative
#   Q.profile.share.relative.all.SPAs[,idx] <- Q.profile.share.relative
#   D.profile.share.relative.all.SPAs[,idx] <- D.profile.share.relative
#
# }
#
# ### For displaying the population prevalence by SPA and LA County
# ### NOTE: THIS TABLE profile.cnt.SPAs IS WHAT IS USED IN THE data.prev TABLE (it is read in as "data" and merged with other tables)
# colnames(profile.cnt.SPAs) = SPA.order
# profile.cnt.SPAs<-round(profile.cnt.SPAs,digits=4)
#
#
#
# profile.cnt.SPAs<-cbind(profile.cnt.SPAs,profiles)
# kable(profile.cnt.SPAs) %>%
#   kable_styling(bootstrap_options = "striped", full_width = F)
#
# colnames(H.profile.share.relative.all.SPAs) = SPA.order
# H.profile.share.relative.all.SPAs <- cbind(H.profile.share.relative.all.SPAs,profiles)
#
# colnames(Q.profile.share.relative.all.SPAs) = SPA.order
# Q.profile.share.relative.all.SPAs <- cbind(Q.profile.share.relative.all.SPAs,profiles)
#
# colnames(D.profile.share.relative.all.SPAs) = SPA.order
# D.profile.share.relative.all.SPAs <- cbind(D.profile.share.relative.all.SPAs,profiles)
#
# # write.csv(profile.cnt.SPAs, file = path(result.dir, "ProfilePrev.GeneralPop.csv"))
# # write.csv(H.profile.share.relative.all.SPAs, file = path(result.dir, "ProfilePrev.HospitalPop.csv"))
# # write.csv(Q.profile.share.relative.all.SPAs, file = path(result.dir, "ProfilePrev.ICUPop.csv"))
# # write.csv(D.profile.share.relative.all.SPAs, file = path(result.dir, "ProfilePrev.DeadPop.csv"))
#
#
# #########################################################################################################
# ### CALCULATED RISK PROBABILITIES
# ### Probability of hospitalization = Pr(H)
# ### Probability of ICU, given hospitalization = Pr(Q)
# ### Probability of death, given ICU = Pr(D)
#
# ### Dataframe with risk probabilities
# risk.probs.SPAs <-
#   data.frame(H.risk.all.SPAs,Q.risk.all.SPAs,D.risk.all.SPAs) %>%
#   mutate(H.risk.all.SPAs = round(H.risk.all.SPAs,3),
#          Q.risk.all.SPAs = round(Q.risk.all.SPAs,3),
#          D.risk.all.SPAs = round(D.risk.all.SPAs,3))
#
# rownames(risk.probs.SPAs) <- SPA.order
# names(risk.probs.SPAs) <- c("Pr(Hospital|Illness)","Pr(ICU|Hosptial)","Pr(Death|ICU)")
#
# kable(risk.probs.SPAs) %>%
#   kable_styling(bootstrap_options = "striped", full_width = F)
#
# write.csv(risk.probs.SPAs, file = path(result.dir, "Over.SPAs.Risk.Probs.csv"))
#
# Alpha.prior.mean <- risk.probs.SPAs[9,1]
# Kappa.prior.mean <- risk.probs.SPAs[9,2]
# Delta.prior.mean <- risk.probs.SPAs[9,3]
#









#########################################################################################################
#########################################################################################################
## **FILTERING** TO GET GROUP-AVERAGED PROBABILITIES OF SEVERE ILLNESS
#########################################################################################################
#########################################################################################################

#########################################################################################################
### Calculate weighted average Pr(H) Pr(Q) Pr(D) for each region

## FULL POPULATION
Pr.H.filter <- Pr.H
Pr.Q.filter <- Pr.Q
Pr.D.filter <- Pr.D

## FILTERED POPULATION
# Pr.H.filter <- filter(Pr.H, Age65.==0 & ComorbidityYes==0)
# Pr.Q.filter <- filter(Pr.Q, Age65.==0 & ComorbidityYes==0)
# Pr.D.filter <- filter(Pr.D, Age65.==0 & ComorbidityYes==0)

# Pr.H.filter <- filter(Pr.H, Age45.64==1 | Age20.44==1)
# Pr.Q.filter <- filter(Pr.Q, Age45.64==1 | Age20.44==1)
# Pr.D.filter <- filter(Pr.D, Age45.64==1 | Age20.44==1)

## FILTER INDEPENDENT
profile.cnt.SPAs <- matrix(0, nrow = nrow(Pr.H.filter), ncol = nrow(Pop.prevalence))
H.profile.share.relative.all.SPAs <- matrix(0, nrow = nrow(Pr.H.filter), ncol = nrow(Pop.prevalence))
Q.profile.share.relative.all.SPAs <- matrix(0, nrow = nrow(Pr.H.filter), ncol = nrow(Pop.prevalence))
D.profile.share.relative.all.SPAs <- matrix(0, nrow = nrow(Pr.H.filter), ncol = nrow(Pop.prevalence))
H.risk.all.SPAs <- c(rep(0,nrow(Pop.prevalence)))
Q.risk.all.SPAs <- c(rep(0,nrow(Pop.prevalence)))
D.risk.all.SPAs <- c(rep(0,nrow(Pop.prevalence)))

remove.50 = FALSE # TRUE
percentage.to.remove = 1


for (idx in 1:nrow(Pop.prevalence)) {

  margprob.SPA <- Pop.prev.matrix[idx,]
  sample.pop.SPA <- rmvbin(10000, margprob=margprob.SPA, sigma=SIGMA2)
  sample.pop.df <- as.data.frame(sample.pop.SPA)
  colnames(sample.pop.df)<-colnames(Pop.prev.matrix)

  ### Create an "any comorbidity" vector
  any.comb <- c(rep(0,nrow(sample.pop.SPA)))

  for (i in 1:nrow(sample.pop.df)) {
    if(sample.pop.df$diabetes[i]==1 || sample.pop.df$hypertension[i]==1 || sample.pop.df$copd[i]==1 || sample.pop.df$coronary[i]==1 || sample.pop.df$cancer[i]==1)
    {any.comb[i]=1}
  }

  ### Create a new sample.pop df with the individual comborbidities deleted and the "any.comb" added
  sample.pop.df <- sample.pop.df %>% dplyr::select(-c(diabetes,hypertension,copd,coronary,cancer))
  sample.pop.df$any.comb <- any.comb

  ### Count population prevalence of profiles (much faster with as.matrix())
  profiles <- as.matrix(dplyr::select(Pr.H.filter, -1))
  sample.pop.table <- as.matrix(sample.pop.df)

  profile.cnt <- c(rep(0,dim(profiles)[1]))
  for (i in 1:dim(profiles)[1]) {
    for (j in 1:dim(sample.pop.table)[1]) {
      if(all(profiles[i,]==sample.pop.table[j,]))
      {profile.cnt[i]<-(profile.cnt[i]+1)}
    }
  }

  ####################################################
  ## FOR REMOVING 50% OF ELDERLY
  ####################################################
  # if (remove.50==TRUE){
  #   profile.cnt.reduce <- profile.cnt
  #   for (k in 1:length(profile.cnt)){
  #     if (profiles[k,"Age65."]==1){
  #       profile.cnt.reduce[k] = profile.cnt.reduce[k]*percentage.to.remove
  #     }
  #   }
  #
  #   profile.cnt <- profile.cnt.reduce
  # }
  ####################################################
  ####################################################

  ### Get frequency distribution of profiles
  profile.cnt.freq <- profile.cnt/sum(profile.cnt)
  profile.cnt.SPAs[,idx]<-profile.cnt.freq
  print(idx)
  print(round(profile.cnt.freq,digits=3))

  ### Calculate weighted average risk probability for the SPA across all profiles:
  ### H given general population, Q given H population, D given Q population

  # Profile prevalence within general population:
  pop.profile.share.relative <- profile.cnt.freq

  # Weighted avg for Pr(H): Profile prevalence within general population * Profile specific Pr(H)
  H.profile.share <- pop.profile.share.relative*t(dplyr::select(Pr.H.filter,1))
  H.risk.weighted.avg <- sum(H.profile.share)

  # Profile prevalence with hospitalized population
  H.profile.share.relative <- H.profile.share/(H.risk.weighted.avg)

  print(round(H.profile.share.relative,digits=3))


  # Weighted avg for Pr(Q): Profile prevalence within hospitalized population * Profile specific Pr(Q)
  Q.profile.share <- H.profile.share.relative*t(dplyr::select(Pr.Q.filter,1))
  Q.risk.weighted.avg <- sum(Q.profile.share)

  # Profile prevalence within ICU population
  Q.profile.share.relative <- Q.profile.share/(Q.risk.weighted.avg)

  # Weighted avg for Pr(D): Profile prevalence within ICU population * Profile specific Pr(D)
  D.profile.share <- Q.profile.share.relative*t(dplyr::select(Pr.D.filter,1))
  D.risk.weighted.avg <- sum(D.profile.share)

  # Profile prevalence within dead population (used later)
  D.profile.share.relative <- D.profile.share/(D.risk.weighted.avg)

  ### Save the weighted risk probabilities in a vector
  H.risk.all.SPAs[idx] = H.risk.weighted.avg
  Q.risk.all.SPAs[idx] = Q.risk.weighted.avg
  D.risk.all.SPAs[idx] = D.risk.weighted.avg

  ### Save the relative share of each profile in a matrix
  H.profile.share.relative.all.SPAs[,idx] <- H.profile.share.relative
  Q.profile.share.relative.all.SPAs[,idx] <- Q.profile.share.relative
  D.profile.share.relative.all.SPAs[,idx] <- D.profile.share.relative

}

### For displaying the population prevalence by SPA and LA County
### NOTE: THIS TABLE profile.cnt.SPAs IS WHAT IS USED IN THE data.prev TABLE (it is read in as "data" and merged with other tables)
colnames(profile.cnt.SPAs) = SPA.order
profile.cnt.SPAs<-round(profile.cnt.SPAs,digits=5)

profile.cnt.SPAs<-cbind(profile.cnt.SPAs,profiles)
kable(profile.cnt.SPAs) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

colnames(H.profile.share.relative.all.SPAs) = SPA.order
H.profile.share.relative.all.SPAs <- cbind(H.profile.share.relative.all.SPAs,profiles)

colnames(Q.profile.share.relative.all.SPAs) = SPA.order
Q.profile.share.relative.all.SPAs <- cbind(Q.profile.share.relative.all.SPAs,profiles)

colnames(D.profile.share.relative.all.SPAs) = SPA.order
D.profile.share.relative.all.SPAs <- cbind(D.profile.share.relative.all.SPAs,profiles)

# write.csv(profile.cnt.SPAs, file = path(result.dir, "ProfilePrev.GeneralPop.csv"))
# write.csv(H.profile.share.relative.all.SPAs, file = path(result.dir, "ProfilePrev.HospitalPop.csv"))
# write.csv(Q.profile.share.relative.all.SPAs, file = path(result.dir, "ProfilePrev.ICUPop.csv"))
# write.csv(D.profile.share.relative.all.SPAs, file = path(result.dir, "ProfilePrev.DeadPop.csv"))


#########################################################################################################
### CALCULATED RISK PROBABILITIES
### Probability of hospitalization = Pr(H)
### Probability of ICU, given hospitalization = Pr(Q)
### Probability of death, given ICU = Pr(D)

### Dataframe with risk probabilities
risk.probs.SPAs <-
  data.frame(H.risk.all.SPAs,Q.risk.all.SPAs,D.risk.all.SPAs) %>%
  mutate(H.risk.all.SPAs = round(H.risk.all.SPAs,3),
         Q.risk.all.SPAs = round(Q.risk.all.SPAs,3),
         D.risk.all.SPAs = round(D.risk.all.SPAs,3))

rownames(risk.probs.SPAs) <- SPA.order
names(risk.probs.SPAs) <- c("Pr(Hospital|Illness)","Pr(ICU|Hosptial)","Pr(Death|ICU)")

risk.probs.LAC.filter <- risk.probs.SPAs[9,]

# kable(risk.probs.LAC.filter) %>%
#   kable_styling(bootstrap_options = "striped", full_width = F)

#write.csv(risk.probs.SPAs, file = path(result.dir, "Over.SPAs.Risk.Probs.csv"))

# Alpha.filter.prior.mean.orig <- risk.probs.SPAs[9,1]
# Kappa.filter.prior.mean.orig <- risk.probs.SPAs[9,2]
# Delta.filter.prior.mean.orig <- risk.probs.SPAs[9,3]

# Alpha.filter.prior.mean.50 <- risk.probs.SPAs[9,1]
# Kappa.filter.prior.mean.50 <- risk.probs.SPAs[9,2]
# Delta.filter.prior.mean.50 <- risk.probs.SPAs[9,3]

Alpha.filter.prior.mean <- risk.probs.SPAs[9,1]
Kappa.filter.prior.mean <- risk.probs.SPAs[9,2]
Delta.filter.prior.mean <- risk.probs.SPAs[9,3]

#########################################################################################################
### CALCULATING NUMBERS OF INDIVIDUALS REMOVED BY SHIELDING SCENARIOS
# pop.prev.No65.NoComorbidity <- 1 - sum( filter(as.data.frame(profile.cnt.SPAs), Age65.==0 & ComorbidityYes==0) %>% select('LA County') )
# pop.prev.NoComorbidity <- 1 - sum( filter(as.data.frame(profile.cnt.SPAs), ComorbidityYes==0) %>% select('LA County') )
# pop.prev.No65 <- 1 - sum( filter(as.data.frame(profile.cnt.SPAs), Age65.==0) %>% select('LA County') )















#########################################################################################################
#########################################################################################################
## LAC OBSERVED PREVALENCE IN ILLNESSES
#########################################################################################################
#########################################################################################################

#########################################################################################################
### STEP 0: ABOVE -- ESTIMATING POPULATION PREVALENCE OF EACH RISK PROFILE
# (also H, Q, D populations using only raw risk model without baseline calculations, which could be removed,
# but I'm saving it because it has the FILTER code for isolating e.g. 65+)
#########################################################################################################

#########################################################################################################
### STEP 1: PINNING PREVALENCE OF INFECTION TO OBSERVED ILLNESS DATA FOR EACH RISK PROFILE
# This takes in the estimated prevalence of each risk profile as estimated in Step 0
# Takes in LAC data on distribution of age groups
#########################################################################################################

#Get observed LAC Age prevalence in Illnesses
n.dates.LAC.obs.age <- 2
freq.LAC.obs.age <- matrix(nrow=3, ncol=n.dates.LAC.obs.age)

freq.LAC.obs.age[,1] <- c(0.016, 0.75, 0.233)
freq.LAC.obs.age[,2] <- c(0.089, 0.794, 0.117)

# TESTING VALUES
# freq.LAC.obs.age[,1] <- c(.01, .49, 0.5) #c(0.016, 0.75, 0.233)
# freq.LAC.obs.age[,2] <- c(0.5, .49, 0.01) #c(0.089, 0.794, 0.117)

colnames(freq.LAC.obs.age) <- c("Apr.20","Jul.20")
rownames(freq.LAC.obs.age) <- c("Age0.19","Age20.64","Age65.")
freq.LAC.obs.age <- as.data.frame(freq.LAC.obs.age)

#Extract the population prevalence calculated above
#Change the profile numbers to factors and name the variable
Profile <- factor(seq(1,nrow(profile.cnt.SPAs)))
profile.freq.vec.MODEL <- as.data.frame(cbind(Profile,profile.cnt.SPAs[,c(9:ncol(profile.cnt.SPAs))]))

#Get the sum of prevalences of each age group
freq.sum.0.19 <- colSums(filter(profile.freq.vec.MODEL, Age0.19==1))['LA County']
freq.sum.20.64 <- colSums(filter(profile.freq.vec.MODEL, Age20.44==1 | Age45.64==1))['LA County']
freq.sum.65 <- colSums(filter(profile.freq.vec.MODEL, Age65.==1))['LA County']

freq.sum.age <- matrix(nrow=3, ncol=1)
freq.sum.age[1] <- freq.sum.0.19
freq.sum.age[2] <- freq.sum.20.64
freq.sum.age[3] <- freq.sum.65
rownames(freq.sum.age) <- c("Age0.19","Age20.64","Age65.")
colnames(freq.sum.age) <- c("freq.sum.age")
freq.sum.age.MODEL<-as.data.frame(freq.sum.age)

## LOOP TO GET PROFILE PREVALENCES RENORMALIZED BASED ON LAC OBSERVED AGE PREVALENCE IN ILLNESSES
n.profiles <- nrow(profile.freq.vec.MODEL)
profile.freq.LAC.EST <- matrix(nrow=n.profiles, ncol=n.dates.LAC.obs.age)

for (date.no in 1:n.dates.LAC.obs.age){

  profile.freq.vec.LAC.DATE <- c(rep(0,n.profiles)) #Renormalize
  age.group.freq.LAC.DATE <- (freq.LAC.obs.age[,date.no])
  names(age.group.freq.LAC.DATE) <- rownames(freq.LAC.obs.age)

  ## For each age group, find the % of that age group of profileXX, then multiply by the LAC.observed % of that age group

  for (idx in 1:n.profiles){

    if (profile.freq.vec.MODEL$Age0.19[idx] == 1){
      profile.freq.vec.LAC.DATE[idx] <-
        (profile.freq.vec.MODEL$'LA County'[idx] / freq.sum.age.MODEL[1,]) * (age.group.freq.LAC.DATE["Age0.19"])
    }
    else if (profile.freq.vec.MODEL$Age20.44[idx] == 1 | profile.freq.vec.MODEL$Age45.64[idx] == 1){
      profile.freq.vec.LAC.DATE[idx] <-
        (profile.freq.vec.MODEL$'LA County'[idx] / freq.sum.age.MODEL[2,]) * (age.group.freq.LAC.DATE["Age20.64"])
    }
    else if (profile.freq.vec.MODEL$Age65.[idx] == 1){
      profile.freq.vec.LAC.DATE[idx] <-
        (profile.freq.vec.MODEL$'LA County'[idx] / freq.sum.age.MODEL[3,]) * (age.group.freq.LAC.DATE["Age65."])
    }
  }
  profile.freq.LAC.EST[,date.no] <- round(profile.freq.vec.LAC.DATE,digits=10)
}

colnames(profile.freq.LAC.EST) <- colnames(freq.LAC.obs.age)

## THIS IS THE RENORMALIZED PREVALENCE OF EACH RISK PROFILE PINNED TO LAC OBSERVED DATA BY AGE GROUP
Profile <- factor(seq(1,nrow(profile.cnt.SPAs)))
profile.freq.LAC.EST <- as.data.frame(profile.freq.LAC.EST)
profile.freq.LAC.EST.USE <- cbind(Profile,profile.freq.LAC.EST)


#########################################################################################################
### STEP 2A: PINNING P(H|I) P(Q|H) P(D|Q) BY RISK PROFILE TO EPIDEMIC MODEL ESTIMATES BY CHANGING BASELINES
#########################################################################################################













#########################################################################################################
### STEP 2: PINNING PREVALENCE OF INFECTION TO OBSERVED ILLNESS DATA FOR EACH RISK PROFILE
#########################################################################################################

#########################################################################################################
### Calculate weighted average Pr(H) Pr(Q) Pr(D) for each date

## INITIALIZE

#########################################################################################################
### GET EPI MODEL ALPHA, KAPPA, DELTA AVERAGES

risk.probs.POSTERIORS.1 <- ABC.par.stats[1,] %>% select(c("Pr(H|I)1", "Pr(Q|H)1", "Pr(D|Q)1" ))
risk.probs.POSTERIORS.2 <- as.data.frame(ABC.par.stats[1,] %>% select(c("Pr(H|I)2", "Pr(Q|H)2", "Pr(D|Q)2" )))
risk.probs.POSTERIORS <- rbind(as.list(risk.probs.POSTERIORS.1),as.list(risk.probs.POSTERIORS.2))
rownames(risk.probs.POSTERIORS) <- c("Apr.20","Jul.20")
colnames(risk.probs.POSTERIORS) <- c("Alpha","Kappa","Delta")

#########################################################################################################
### GET POPULATION PREVALENCE OF EACH PROFILE IN THE GENERAL POPULATION (calculated in STEP 0)
profile.freq.LAC.EST <- profile.freq.LAC.EST

#########################################################################################################
### GET RISK MODEL (JAM) ESTIMATES OF P(H|I) P(Q|D) P(D|Q) FOR EACH RISK PROFILE
### AND WEIGHTED AVG (calculated in STEP 0)

Pr.H.JAM <- t(dplyr::select(Pr.H,1))
Pr.Q.JAM <- t(dplyr::select(Pr.Q,1))
Pr.D.JAM <- t(dplyr::select(Pr.D,1))
#H.risk.weighted.avg.ORIG <- risk.probs.DATES[,1]

#########################################################################################################
### Initialize
profile.cnt.DATES.UPDATE <- matrix(0, nrow = length(Profile), ncol = n.dates.LAC.obs.age)

Pr.H.DATES.UPDATE <- matrix(0, nrow = nrow(Pr.H), ncol = n.dates.LAC.obs.age)
Pr.Q.DATES.UPDATE <- matrix(0, nrow = nrow(Pr.H), ncol = n.dates.LAC.obs.age)
Pr.D.DATES.UPDATE <- matrix(0, nrow = nrow(Pr.H), ncol = n.dates.LAC.obs.age)

H.profile.share.relative.all.DATES.UPDATE <- matrix(0, nrow = nrow(Pr.H), ncol = n.dates.LAC.obs.age)
Q.profile.share.relative.all.DATES.UPDATE <- matrix(0, nrow = nrow(Pr.H), ncol = n.dates.LAC.obs.age)
D.profile.share.relative.all.DATES.UPDATE <- matrix(0, nrow = nrow(Pr.H), ncol = n.dates.LAC.obs.age)

H.risk.all.DATES.UPDATE <- c(rep(0,n.dates.LAC.obs.age))
Q.risk.all.DATES.UPDATE <- c(rep(0,n.dates.LAC.obs.age))
D.risk.all.DATES.UPDATE <- c(rep(0,n.dates.LAC.obs.age))

#########################################################################################################
### CALCULATIONS FOR UPDATED PREVALENCE OF EACH PROFILE PINNED TO LAC DATA + EPI MODEL ESTIMATES

## Function to truncate updated probabilities to stay between 0 and 1
truncate.0.1 <- function(x) pmin( pmax(x,.0001) , 1)
#truncate.0 <- function(x) pmax(x,0)

## Function to leave probabilities of 0 as 0
keep.0 <- function(Pr.JAM,theta){
  Pr.UPDATE <- Pr.JAM
  for (i in 1:length(Pr.JAM)) {
    if (Pr.JAM[i]!=0) Pr.UPDATE[i] <- Pr.JAM[i] - theta
    else if (Pr.JAM[i]==0) Pr.UPDATE[i] <- Pr.JAM[i]
  }
  return(Pr.UPDATE)
}


for (idx in 1:n.dates.LAC.obs.age) {

  ### EXTRACT VALUES FROM idx DATE
  profile.cnt.freq <- profile.freq.LAC.EST[,idx]
  H.risk.weighted.avg.EPI <- as.numeric(risk.probs.POSTERIORS[idx,1])
  Q.risk.weighted.avg.EPI <- as.numeric(risk.probs.POSTERIORS[idx,2])
  D.risk.weighted.avg.EPI <- as.numeric(risk.probs.POSTERIORS[idx,3])

  ### SAVE FOR LATER frequency distribution of profiles into profile.
  profile.cnt.DATES.UPDATE[,idx]<-profile.cnt.freq
  print(idx)
  print(profile.cnt.freq)

  ### Calculate weighted average risk probability for the SPA across all profiles:
  ### H given ILLNESSES OBSERVED BY AGE GROUP, Q given H population, D given Q population

  ##############################################################################################################
  ## UPDATE 090320: RECALCULATE H.profile.share SO IT TAKES IN:
  ##                1) profile.cnt.freq AS UPDATED BY PEGGING TO LAC DATA ON AGE GROUPS
  ##                2) UPDATED BASELINE PROBABILITY SO THAT WEIGHTED AVG OVER ALL PROFILES EQUALS ALPHA

  # Profile prevalence within general population:
  pop.profile.share.relative <- profile.cnt.freq

  # 0-ALPHA) GET REDUCTION TERM FOR ALPHA: theta.ALPHA
  theta.ALPHA <- sum( pop.profile.share.relative * Pr.H.JAM) - H.risk.weighted.avg.EPI

  # 1-ALPHA) UPDATE Pr.H WITH theta.ALPHA (avoiding negative values)
  Pr.H.UPDATE <- truncate.0.1(  keep.0(Pr.H.JAM, theta.ALPHA) )

  # 2-ALPHA) UPDATE H.profile.share
  H.profile.share.UPDATE <- pop.profile.share.relative*Pr.H.UPDATE

  # 3-ALPHA) UPDATE H.profile.share.relative (SHOULD SUM TO 1)
  H.profile.share.relative.UPDATE <- H.profile.share.UPDATE / sum(H.profile.share.UPDATE)  #H.risk.weighted.avg.EPI

  print(sum(H.profile.share.relative.UPDATE))

  ##############################################################################################################
  ## UPDATE 090320: RECALCULATE Q.profile.share

  # 0-KAPPA) GET REDUCTION TERM FOR KAPPA: theta.KAPPA
  theta.KAPPA <- sum( H.profile.share.relative.UPDATE * Pr.Q.JAM) - Q.risk.weighted.avg.EPI

  # 1-KAPPA) UPDATE Pr.K WITH theta.KAPPA (avoiding negative values) (leaving 0's as 0's)
  #Pr.Q.UPDATE <- truncate.0.1( Pr.Q.JAM - theta.KAPPA )
  Pr.Q.UPDATE <- truncate.0.1( keep.0(Pr.Q.JAM, theta.KAPPA) )

  # 2-KAPPA) UPDATE Q.profile.share
  Q.profile.share.UPDATE <- H.profile.share.relative.UPDATE*Pr.Q.UPDATE

  # 3-KAPPA) UPDATE Q.profile.share.relative (SHOULD SUM TO 1)
  Q.profile.share.relative.UPDATE <- Q.profile.share.UPDATE / sum(Q.profile.share.UPDATE)  #Q.risk.weighted.avg.EPI

  print(sum(Q.profile.share.relative.UPDATE))

  ##############################################################################################################
  ## UPDATE 090320: RECALCULATE D.profile.share

  # 0-DELTA) GET REDUCTION TERM FOR DELTA: theta.DELTA
  theta.DELTA <- sum( Q.profile.share.relative.UPDATE * Pr.D.JAM) - D.risk.weighted.avg.EPI

  # 1-DELTA) UPDATE Pr.D WITH theta.DELTA (avoiding negative values) (leaving 0's as 0's)
  #Pr.D.UPDATE <- truncate.0.1( Pr.D.JAM - theta.DELTA )
  Pr.D.UPDATE <- truncate.0.1( keep.0(Pr.D.JAM, theta.DELTA) )

  # 2-DELTA) UPDATE D.profile.share
  D.profile.share.UPDATE <- Q.profile.share.relative.UPDATE*Pr.D.UPDATE

  ## Check population average update is same as D.risk.weighted.avg.EPI
  print(sum(D.profile.share.UPDATE))
  print(D.risk.weighted.avg.EPI)

  # 3-D) UPDATE D.profile.share.relative (SHOULD SUM TO 1)
  D.profile.share.relative.UPDATE <- D.profile.share.UPDATE / sum(D.profile.share.UPDATE) #D.risk.weighted.avg.EPI

  # Check the D.profile.share.relative.UPDATE population sums to 1
  print(sum(D.profile.share.relative.UPDATE))

  ##############################################################################################################
  ## SAVE FILES

  ### Save the weighted risk probabilities in a vector
  H.risk.all.DATES.UPDATE[idx] = sum(H.profile.share.UPDATE)
  Q.risk.all.DATES.UPDATE[idx] = sum(Q.profile.share.UPDATE)
  D.risk.all.DATES.UPDATE[idx] = sum(D.profile.share.UPDATE)

  ### Save the relative share of each profile in a matrix
  H.profile.share.relative.all.DATES.UPDATE[,idx] <- round(H.profile.share.relative.UPDATE, 5)
  Q.profile.share.relative.all.DATES.UPDATE[,idx] <- round(Q.profile.share.relative.UPDATE, 5)
  D.profile.share.relative.all.DATES.UPDATE[,idx] <- round(D.profile.share.relative.UPDATE, 5)

  ### Save the Pr.UPDATE files in a matrix
  Pr.H.DATES.UPDATE[,idx] <- round(Pr.H.UPDATE, 5)
  Pr.Q.DATES.UPDATE[,idx] <- round(Pr.Q.UPDATE, 5)
  Pr.D.DATES.UPDATE[,idx] <- round(Pr.D.UPDATE, 5)

}

### For displaying the population prevalence by SPA and LA County
### NOTE: THIS TABLE profile.cnt.SPAs IS WHAT IS USED IN THE data.prev TABLE (it is read in as "data" and merged with other tables)
colnames(profile.cnt.DATES.UPDATE) = colnames(freq.LAC.obs.age)
profile.cnt.DATES.UPDATE <- as.data.frame(round(profile.cnt.DATES.UPDATE,digits=5))

profile.cnt.DATES.UPDATE <- cbind(profile.cnt.DATES.UPDATE, profiles) #cbind(Profile, profile.cnt.DATES)
formattable(profile.cnt.DATES.UPDATE)
# kable(profile.cnt.DATES.UPDATE) %>%
#   kable_styling(bootstrap_options = "striped", full_width = F)

colnames(H.profile.share.relative.all.DATES.UPDATE) = colnames(freq.LAC.obs.age)
H.profile.share.relative.all.DATES.UPDATE <- cbind(H.profile.share.relative.all.DATES.UPDATE, profiles) #cbind(Profile, as.data.frame(H.profile.share.relative.all.DATES))
colnames(Q.profile.share.relative.all.DATES.UPDATE) = colnames(freq.LAC.obs.age)
Q.profile.share.relative.all.DATES.UPDATE <- cbind(Q.profile.share.relative.all.DATES.UPDATE, profiles) #cbind(Profile, as.data.frame(Q.profile.share.relative.all.DATES))
colnames(D.profile.share.relative.all.DATES.UPDATE) = colnames(freq.LAC.obs.age)
D.profile.share.relative.all.DATES.UPDATE <- cbind(D.profile.share.relative.all.DATES.UPDATE, profiles) #cbind(Profile, as.data.frame(D.profile.share.relative.all.DATES))


colnames(Pr.H.DATES.UPDATE) = colnames(freq.LAC.obs.age)
Pr.H.DATES.UPDATE <- cbind(Pr.H.DATES.UPDATE, profiles)
colnames(Pr.Q.DATES.UPDATE) = colnames(freq.LAC.obs.age)
Pr.Q.DATES.UPDATE <- cbind(Pr.Q.DATES.UPDATE, profiles)
colnames(Pr.D.DATES.UPDATE) = colnames(freq.LAC.obs.age)
Pr.D.DATES.UPDATE <- cbind(Pr.D.DATES.UPDATE, profiles)


# write.csv(profile.cnt.SPAs, file = path(result.dir, "ProfilePrev.GeneralPop.csv"))
# write.csv(H.profile.share.relative.all.SPAs, file = path(result.dir, "ProfilePrev.HospitalPop.csv"))
# write.csv(Q.profile.share.relative.all.SPAs, file = path(result.dir, "ProfilePrev.ICUPop.csv"))
# write.csv(D.profile.share.relative.all.SPAs, file = path(result.dir, "ProfilePrev.DeadPop.csv"))


#########################################################################################################
### CALCULATED RISK PROBABILITIES
### Probability of hospitalization, given illness = Pr(H)
### Probability of ICU, given hospitalization = Pr(Q)
### Probability of death, given ICU = Pr(D)

### Dataframe with risk probabilities
risk.probs.DATES.UPDATE <-
  data.frame(H.risk.all.DATES.UPDATE,Q.risk.all.DATES.UPDATE,D.risk.all.DATES.UPDATE) %>%
  mutate(H.risk.all.DATES.UPDATE = round(H.risk.all.DATES.UPDATE,3),
         Q.risk.all.DATES.UPDATE = round(Q.risk.all.DATES.UPDATE,3),
         D.risk.all.DATES.UPDATE = round(D.risk.all.DATES.UPDATE,3))

rownames(risk.probs.DATES.UPDATE) <- colnames(freq.LAC.obs.age)
names(risk.probs.DATES.UPDATE) <- c("Pr(H|I)","Pr(Q|H)","Pr(D|Q)")

# kable(risk.probs.DATES) %>%
#   kable_styling(bootstrap_options = "striped", full_width = F)


#write.csv(risk.probs.SPAs, file = path(result.dir, "Over.SPAs.Risk.Probs.csv"))

Alpha.LAC.OBS.EST.UPDATE <- risk.probs.DATES.UPDATE[,1]
Kappa.LAC.OBS.EST.UPDATE <- risk.probs.DATES.UPDATE[,2]
Delta.LAC.OBS.EST.UPDATE <- risk.probs.DATES.UPDATE[,3]


formattable(risk.probs.DATES.UPDATE)






