
###############################################################################################################
## CALCULATE RISK PROBABILITIES
## V2 - UPDATING PR(Q) WITH POP PREVALENCE OF PR(H)
###############################################################################################################


###############################################################################################################
### Read in calculated risk profiles (JAM model estimates) and marginal population prevalences

#data.dir="/Users/abigailhorn/Dropbox/0 2019/COVID-19/LACounty_modeling/data/corrmats/Ordinal.Age.Binary.Comb_2020_04_03/"
#marginalRR <- read.table(paste0(data.dir, "Ordinal.Comb.marginE.input.txt"), sep=" ", header=TRUE )

data.dir = here("/data/")

### Read in risk profiles and probaiblities generated by JAM
Pr.D = read.table(path(data.dir, "Ordinal.Age.DummyRiskProfile.Death.txt"), sep=" ", header=TRUE )
Pr.H = read.table(path(data.dir, "Ordinal.Age.DummyRiskProfile.Hospitalization.txt"), sep=" ", header=TRUE )
Pr.Q = read.table(path(data.dir, "Ordinal.Age.DummyRiskProfile.ICU.txt"), sep=" ", header=TRUE )

### Delete first row -- is error
Pr.D <- Pr.D[-1,]
Pr.H <- Pr.H[-1,]
Pr.Q <- Pr.Q[-1,]

### Add age group 20-44 and age group 0-19 (only 2 profiles needed, assuming comorbidities = 0)
add.probs.mat <- function(Probs.mat,baseline.prob){
  Age20.44 <- rep(0, times = dim(Probs.mat)[1])
  for (i in 1:dim(Probs.mat)[1]){
    if( (Probs.mat$Age45.64[i]==0) & (Probs.mat$Age65.[i]==0)) {Age20.44[i]=1}
  }
  Probs.mat <- as.data.frame(append(Probs.mat, list(Age20.44 = Age20.44), after = 1))
  ### Add age group 0 (<20 yrs and male) to profiles
  Probs.mat<-as.data.frame(append(Probs.mat, list(age.0.19 = rep(0, times=dim(Probs.mat)[1])), after = 1))
  Probs.mat<-rbind(Probs.mat, c(baseline.prob,1,0,0,0,1,0,0,0))
  Probs.mat<-rbind(Probs.mat, c(baseline.prob,1,0,0,0,0,0,0,0))
  return(Probs.mat)
}
Pr.H<-add.probs.mat(Pr.H,0.025)
Pr.Q<-add.probs.mat(Pr.Q,0)
Pr.D<-add.probs.mat(Pr.D,0)

data.dir = here("/results/")
write.csv(Pr.H, file = path(data.dir, "Ordinal.Comb.Pr.H.ByProfile.csv"))
write.csv(Pr.Q, file = path(data.dir, "Ordinal.Comb.Pr.Q.ByProfile.csv"))
write.csv(Pr.D, file = path(data.dir, "Ordinal.Comb.Pr.D.ByProfile.csv"))


#########################################################################################################
## KEY RISK PROFILES
data.dir=here("/data/")
Pr.D.FULL = read.table(path(data.dir, "Ordinal.Age.DummyRiskProfile.Death.txt"), sep=" ", header=TRUE )

risk_profiles_FULL <- Pr.D.FULL[,-1]

#########################################################################################################
### POPULATION RISK FACTOR PREVALENCE FOR LA COUNTY
### Data coming from [Los Angeles County Health Survey](http://www.publichealth.lacounty.gov/ha/hasurveyintro.htm)

data.dir=here("/data/")
SIGMA2 = read.csv(path(data.dir, "Pop.prevalence.corr.csv"), sep=",", header=TRUE,row.names = 1)
Pop.prevalence = read.csv(path(data.dir, "Pop.prevalence.csv"), sep=",", header=TRUE,row.names = 1 )
Pop.prev.matrix<-as.matrix(Pop.prevalence)

### Keep track of which index corresponds to which SPA
#rownames(risk.probs.SPAs) <- SPA.order
#colnames(profile.cnt.SPAs) = SPA.order
SPA.order <- rownames(Pop.prev.matrix)

### Format table
Pop.prevalence.format<-Pop.prevalence
colnames(Pop.prevalence.format)[5]<-"gender.Male"

#########################################################################################################
### Calculate weighted average Pr(H) Pr(Q) Pr(D) for each region

## Initialize
H.risk.all.SPAs <- c(rep(0,dim(Pop.prevalence)[1]))
Q.risk.all.SPAs <- c(rep(0,dim(Pop.prevalence)[1]))
D.risk.all.SPAs <- c(rep(0,dim(Pop.prevalence)[1]))
profile.cnt.SPAs <- matrix(0, nrow = dim(Pr.H)[1], ncol = dim(Pop.prevalence)[1])
H.profile.share.relative.all.SPAs <- matrix(0, nrow = nrow(Pr.H), ncol = nrow(Pop.prevalence))
Q.profile.share.relative.all.SPAs <- matrix(0, nrow = nrow(Pr.H), ncol = nrow(Pop.prevalence))
D.profile.share.relative.all.SPAs <- matrix(0, nrow = nrow(Pr.H), ncol = nrow(Pop.prevalence))

for (idx in 1:nrow(Pop.prevalence)) {

  margprob.SPA <- Pop.prev.matrix[idx,]
  sample.pop.SPA <- rmvbin(5000, margprob=margprob.SPA, sigma=SIGMA2)
  sample.pop.df <- as.data.frame(sample.pop.SPA)
  colnames(sample.pop.df)<-colnames(Pop.prev.matrix)

  ### Create an "any comorbidity" vector
  any.comb <- c(rep(0,dim(sample.pop.SPA)[1]))
  for (i in 1:dim(sample.pop.SPA)[1]) {
    if(sample.pop.SPA[i,7]==1 || sample.pop.SPA[i,8]==1 || sample.pop.SPA[i,9]==1 || sample.pop.SPA[i,10]==1){any.comb[i]=1}
  }

  ### Create a new sample.pop df with the individual comborbidities deleted and the "any.comb" added
  sample.pop.df <- sample.pop.df %>% dplyr::select(-c(7:10))
  sample.pop.df$any.comb <- any.comb

  ### Count population prevalence of profiles
  profiles <- as.matrix(dplyr::select(Pr.H, -1))

  profile.cnt <- c(rep(0,dim(profiles)[1]))
  for (i in 1:dim(profiles)[1]) {
    for (j in 1:dim(sample.pop.df)[1]) {
      if(all(profiles[i,]==sample.pop.df[j,]))
      {profile.cnt[i]<-(profile.cnt[i]+1)}
    }
  }
  #print(profile.cnt)

  ### Get frequency distribution of profiles
  profile.cnt.freq <- profile.cnt/sum(profile.cnt)
  profile.cnt.SPAs[,idx]<-profile.cnt.freq
  print(idx)
  print(round(profile.cnt.freq,digits=3))

  ### Calculate weighted average risk probability for the SPA across all profiles:
  ### H given general population, Q given H population, D given Q population

  # Profile prevalence within general population:
  pop.profile.share.relative <- profile.cnt.freq

  # Weighted avg for Pr(H): Profile prevalence within general population * Profile specific Pr(H)
  H.profile.share <- pop.profile.share.relative*t(dplyr::select(Pr.H,1))
  H.risk.weighted.avg <- sum(H.profile.share)

  # Profile prevalence with hospitalized population
  H.profile.share.relative <- H.profile.share/(H.risk.weighted.avg)

  print(round(H.profile.share.relative,digits=3))


  # Weighted avg for Pr(Q): Profile prevalence within hospitalized population * Profile specific Pr(Q)
  Q.profile.share <- H.profile.share.relative*t(dplyr::select(Pr.Q,1))
  Q.risk.weighted.avg <- sum(Q.profile.share)

  # Profile prevalence within ICU population
  Q.profile.share.relative <- Q.profile.share/(Q.risk.weighted.avg)

  # Weighted avg for Pr(D): Profile prevalence within ICU population * Profile specific Pr(D)
  D.profile.share <- Q.profile.share.relative*t(dplyr::select(Pr.D,1))
  D.risk.weighted.avg <- sum(D.profile.share)

  # Profile prevalence within dead population (used later)
  D.profile.share.relative <- D.profile.share/(D.risk.weighted.avg)

  ### Save the weighted risk probabilities in a vector
  H.risk.all.SPAs[idx] = H.risk.weighted.avg
  Q.risk.all.SPAs[idx] = Q.risk.weighted.avg
  D.risk.all.SPAs[idx] = D.risk.weighted.avg

  ### Save the relative share of each profile in a matrix
  H.profile.share.relative.all.SPAs[,idx] <- H.profile.share.relative
  Q.profile.share.relative.all.SPAs[,idx] <- Q.profile.share.relative
  D.profile.share.relative.all.SPAs[,idx] <- D.profile.share.relative

}

### For displaying the population prevalence by SPA
colnames(profile.cnt.SPAs) = SPA.order
profile.cnt.SPAs<-round(profile.cnt.SPAs,digits=3)
profile.cnt.SPAs<-cbind(profile.cnt.SPAs,profiles)
# kable(profile.cnt.SPAs) %>%
#   kable_styling(bootstrap_options = "striped", full_width = F)

colnames(H.profile.share.relative.all.SPAs) = SPA.order
H.profile.share.relative.all.SPAs <- cbind(H.profile.share.relative.all.SPAs,profiles)

colnames(Q.profile.share.relative.all.SPAs) = SPA.order
Q.profile.share.relative.all.SPAs <- cbind(Q.profile.share.relative.all.SPAs,profiles)

colnames(D.profile.share.relative.all.SPAs) = SPA.order
D.profile.share.relative.all.SPAs <- cbind(D.profile.share.relative.all.SPAs,profiles)

data.dir = here("/results/")
# write.csv(profile.cnt.SPAs, file = paste0(data.dir, "Ordinal.Comb.ProfilePrev.GeneralPop.csv"))
# write.csv(H.profile.share.relative.all.SPAs, file = paste0(data.dir, "Ordinal.Comb.ProfilePrev.HospitalPop.csv"))
# write.csv(Q.profile.share.relative.all.SPAs, file = paste0(data.dir, "Ordinal.Comb.ProfilePrev.ICUPop.csv"))
# write.csv(D.profile.share.relative.all.SPAs, file = paste0(data.dir, "Ordinal.Comb.ProfilePrev.DeadPop.csv"))


#########################################################################################################
### CALCULATED RISK PROBABILITIES
### Probability of hospitalization = Pr(H)
### Probability of ICU, given hospitalization = Pr(Q)
### Probability of death, given ICU = Pr(D)

### Dataframe with risk probabilities
risk.probs.SPAs <-
  data.frame(H.risk.all.SPAs,Q.risk.all.SPAs,D.risk.all.SPAs) %>%
  mutate(H.risk.all.SPAs = round(H.risk.all.SPAs,5),
         Q.risk.all.SPAs = round(Q.risk.all.SPAs,5), D.risk.all.SPAs = round(D.risk.all.SPAs,5))

rownames(risk.probs.SPAs) <- SPA.order
names(risk.probs.SPAs) <- c("Pr(H)","Pr(Q)","Pr(D)")

# data.dir = "/Users/abigailhorn/Dropbox/0 2019/COVID-19/LACounty_modeling/LADPH_breifing/results/"
# write.csv(risk.probs.SPAs, file = paste0(data.dir, "Ordinal.Comb.Overall.Risk.Probs.csv"))

Alpha.prior.mean <- risk.probs.SPAs[9,1]
Kappa.prior.mean <- risk.probs.SPAs[9,2]
Delta.prior.mean <- risk.probs.SPAs[9,3]
