
###############################################################################################################
## CALCULATE RISK PROBABILITIES
## UPDATING PR(Q) WITH POP PREVALENCE OF PR(H)
## ADDING OBESITY
###############################################################################################################


###############################################################################################################
### Read in calculated risk profiles (JAM model estimates) and marginal population prevalences

### Read in risk profiles and probaiblities generated by JAM
Pr.H.readin = read.table(paste0(data.dir, "Ordinal.Obesity.DummyRiskProfile.Hospitalization.txt"), sep=" ", header=TRUE )
Pr.Q.readin = read.table(paste0(data.dir, "Ordinal.Obesity.DummyRiskProfile.ICU.txt"), sep=" ", header=TRUE )
Pr.D.readin = read.table(paste0(data.dir, "Ordinal.Obesity.DummyRiskProfile.Death.txt"), sep=" ", header=TRUE )

### Add the 3 weight statuses
add.probs.mat <- function(Probs.mat){
  ## Copy first row
  first.row <- Probs.mat[1,]
  n <- 2
  replicated <- do.call("rbind", replicate(n, first.row, simplify=FALSE))
  Probs.mat <- rbind(replicated, Probs.mat)

  ## Add weight status
  Probs.mat$ObesityBMI.30[1] = 1
  Probs.mat$ObesityBMI30.40[2] = 1
  Probs.mat$ObesityBMI.40[3] = 1

  return(Probs.mat)
}
Pr.H <- add.probs.mat(Pr.H.readin)
Pr.Q <- add.probs.mat(Pr.Q.readin)
Pr.D <- add.probs.mat(Pr.D.readin)

### Write output if sharing
# data.dir = "/Users/abigailhorn/Dropbox/0 2019/COVID-19/LACounty_modeling/Website/out/"
# write.csv(Pr.H, file = paste0(data.dir, "Pr.H.BMI.csv"))
# write.csv(Pr.Q, file = paste0(data.dir, "Pr.Q.BMI.csv"))
# write.csv(Pr.D, file = paste0(data.dir, "Pr.D.BMI.csv"))

#########################################################################################################
### POPULATION RISK FACTOR PREVALENCE FOR LA COUNTY
### Data coming from [Los Angeles County Health Survey](http://www.publichealth.lacounty.gov/ha/hasurveyintro.htm)

#Pop.prevalence = read.csv(paste0(data.dir, "Pop.prevalence.BMI.csv"), sep=",", header=TRUE,row.names = 1 )
Pop.prevalence = read.csv(paste0(data.dir, "race.stats.csv"), sep=",", header=TRUE,row.names = 1 )
race.pop <- as.numeric(Pop.prevalence$population)
Pop.prevalence <- select(Pop.prevalence,-population)
Pop.prev.matrix<-as.matrix(Pop.prevalence)

SIGMA.BMI = read.csv(paste0(data.dir, "Each.Comb.Corr.Weighted.txt"), sep=" ", header=TRUE,row.names = 1)
SIGMA2 <- select(SIGMA.BMI, -c(stroke,hepB,kidney))
SIGMA2 <- SIGMA2[-c(13,14,16),]
colnames(SIGMA2) <- colnames(Pop.prevalence)
rownames(SIGMA2) <- colnames(Pop.prevalence)

### Keep track of which index corresponds to which race
race.order <- rownames(Pop.prevalence)

#########################################################################################################
### Calculate weighted average Pr(H) Pr(Q) Pr(D) for each region

## Initialize
H.risk.all.races <- c(rep(0,nrow(Pop.prevalence)))
Q.risk.all.races <- c(rep(0,nrow(Pop.prevalence)))
D.risk.all.races <- c(rep(0,nrow(Pop.prevalence)))
profile.cnt.races <- matrix(0, nrow = nrow(Pr.H), ncol = nrow(Pop.prevalence))
H.profile.share.relative.all.races <- matrix(0, nrow = nrow(Pr.H), ncol = nrow(Pop.prevalence))
Q.profile.share.relative.all.races <- matrix(0, nrow = nrow(Pr.H), ncol = nrow(Pop.prevalence))
D.profile.share.relative.all.races <- matrix(0, nrow = nrow(Pr.H), ncol = nrow(Pop.prevalence))

for (idx in 1:nrow(Pop.prevalence)) {

  margprob.race <- Pop.prev.matrix[idx,]
  sample.pop.race <- rmvbin(50000, margprob=margprob.race, sigma=SIGMA2)
  sample.pop.df <- as.data.frame(sample.pop.race)
  colnames(sample.pop.df)<-colnames(Pop.prev.matrix)

  ### Create an "any comorbidity" vector
  any.comb <- c(rep(0,nrow(sample.pop.race)))

  for (i in 1:nrow(sample.pop.df)) {
    if(sample.pop.df$diabetes[i]==1 || sample.pop.df$hypertension[i]==1 || sample.pop.df$copd[i]==1 || sample.pop.df$coronary[i]==1 || sample.pop.df$cancer[i]==1)
    {any.comb[i]=1}
  }

  ### Create a new sample.pop df with the individual comborbidities deleted and the "any.comb" added
  sample.pop.df <- sample.pop.df %>% dplyr::select(-c(diabetes,hypertension,copd,coronary,cancer))
  sample.pop.df$any.comb <- any.comb

  ### Count population prevalence of profiles (much faster with as.matrix())
  profiles <- as.matrix(dplyr::select(Pr.H, -1))
  sample.pop.table <- as.matrix(sample.pop.df)

  profile.cnt <- c(rep(0,dim(profiles)[1]))
  for (i in 1:dim(profiles)[1]) {
    for (j in 1:dim(sample.pop.table)[1]) {
      if(all(profiles[i,]==sample.pop.table[j,]))
      {profile.cnt[i]<-(profile.cnt[i]+1)}
    }
  }

  ### Get frequency distribution of profiles
  profile.cnt.freq <- profile.cnt/sum(profile.cnt)
  profile.cnt.races[,idx]<-profile.cnt.freq
  print(idx)
  print(round(profile.cnt.freq,digits=3))

  ### Calculate weighted average risk probability for the race across all profiles:
  ### H given general population, Q given H population, D given Q population

  # Profile prevalence within general population:
  pop.profile.share.relative <- profile.cnt.freq

  # Weighted avg for Pr(H): Profile prevalence within general population * Profile specific Pr(H)
  H.profile.share <- pop.profile.share.relative*t(dplyr::select(Pr.H,1))
  H.risk.weighted.avg <- sum(H.profile.share)

  # Profile prevalence with hospitalized population
  H.profile.share.relative <- H.profile.share/(H.risk.weighted.avg)

  print(round(H.profile.share.relative,digits=3))


  # Weighted avg for Pr(Q): Profile prevalence within hospitalized population * Profile specific Pr(Q)
  Q.profile.share <- H.profile.share.relative*t(dplyr::select(Pr.Q,1))
  Q.risk.weighted.avg <- sum(Q.profile.share)

  # Profile prevalence within ICU population
  Q.profile.share.relative <- Q.profile.share/(Q.risk.weighted.avg)

  # Weighted avg for Pr(D): Profile prevalence within ICU population * Profile specific Pr(D)
  D.profile.share <- Q.profile.share.relative*t(dplyr::select(Pr.D,1))
  D.risk.weighted.avg <- sum(D.profile.share)

  # Profile prevalence within dead population (used later)
  D.profile.share.relative <- D.profile.share/(D.risk.weighted.avg)

  ### Save the weighted risk probabilities in a vector
  H.risk.all.races[idx] = H.risk.weighted.avg
  Q.risk.all.races[idx] = Q.risk.weighted.avg
  D.risk.all.races[idx] = D.risk.weighted.avg

  ### Save the relative share of each profile in a matrix
  H.profile.share.relative.all.races[,idx] <- H.profile.share.relative
  Q.profile.share.relative.all.races[,idx] <- Q.profile.share.relative
  D.profile.share.relative.all.races[,idx] <- D.profile.share.relative

}

### For displaying the population prevalence by race
colnames(profile.cnt.races) = race.order
profile.cnt.races<-round(profile.cnt.races,digits=3)
profile.cnt.races<-cbind(profile.cnt.races,profiles)
kable(profile.cnt.races) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

colnames(H.profile.share.relative.all.races) = race.order
H.profile.share.relative.all.races <- cbind(H.profile.share.relative.all.races,profiles)

colnames(Q.profile.share.relative.all.races) = race.order
Q.profile.share.relative.all.races <- cbind(Q.profile.share.relative.all.races,profiles)

colnames(D.profile.share.relative.all.races) = race.order
D.profile.share.relative.all.races <- cbind(D.profile.share.relative.all.races,profiles)

# data.dir = "/Users/abigailhorn/Dropbox/0 2019/COVID-19/LACounty_modeling/Website/out/"
# write.csv(profile.cnt.races, file = paste0(data.dir, "ProfilePrev.GeneralPop.csv"))
# write.csv(H.profile.share.relative.all.races, file = paste0(data.dir, "ProfilePrev.HospitalPop.csv"))
# write.csv(Q.profile.share.relative.all.races, file = paste0(data.dir, "ProfilePrev.ICUPop.csv"))
# write.csv(D.profile.share.relative.all.races, file = paste0(data.dir, "ProfilePrev.DeadPop.csv"))


#########################################################################################################
### CALCULATED RISK PROBABILITIES - OUTPUT TO TABLES
### Probability of hospitalization = Pr(H)
### Probability of ICU, given hospitalization = Pr(Q)
### Probability of death, given ICU = Pr(D)

### Dataframe with risk probabilities
risk.probs.races <-
  data.frame(H.risk.all.races,Q.risk.all.races,D.risk.all.races) %>%
  mutate(H.risk.all.races = round(H.risk.all.races,3),
         Q.risk.all.races = round(Q.risk.all.races,3),
         D.risk.all.races = round(D.risk.all.races,3))

rownames(risk.probs.races) <- race.order
names(risk.probs.races) <- c("Pr(Hospital|Illness)","Pr(ICU|Hosptial)","Pr(Death|ICU)")

kable(risk.probs.races) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)


# data.dir = "/Users/abigailhorn/Dropbox/0 2019/COVID-19/LACounty_modeling/Website/out/"
# write.csv(risk.probs.races, file = paste0(data.dir, "Over.races.Risk.Probs.csv"))
#
# Alpha.prior.mean <- risk.probs.races[9,1]
# Kappa.prior.mean <- risk.probs.races[9,2]
# Delta.prior.mean <- risk.probs.races[9,3]



#########################################################################################################
#########################################################################################################
#########################################################################################################
#########################################################################################################
#########################################################################################################
### Calculate H, Q, D relative shares (by profile / race / race)

calc.HQD.shares <- function(Pr.pop,Pr.H,Pr.Q,Pr.D){

  # group prevalence within general population:

  pop.group.share.relative <- Pr.pop / sum(Pr.pop)

  # Weighted avg for Pr(H): group prevalence within general population * group specific Pr(H)
  H.group.share <- pop.group.share.relative*Pr.H   #t(dplyr::select(Pr.H,1))
  H.risk.weighted.avg <- sum(H.group.share)

  # group prevalence with hospitalized population
  H.group.share.relative <- H.group.share/(H.risk.weighted.avg)

  print(round(H.group.share.relative,digits=3))


  # Weighted avg for Pr(Q): group prevalence within hospitalized population * group specific Pr(Q)
  Q.group.share <- H.group.share.relative*Pr.Q
  Q.risk.weighted.avg <- sum(Q.group.share)

  # group prevalence within ICU population
  Q.group.share.relative <- Q.group.share/(Q.risk.weighted.avg)

  # Weighted avg for Pr(D): group prevalence within ICU population * group specific Pr(D)
  D.group.share <- Q.group.share.relative*Pr.D
  D.risk.weighted.avg <- sum(D.group.share)

  # group prevalence within dead population (used later)
  D.group.share.relative <- D.group.share/(D.risk.weighted.avg)

  relative.shares <- cbind(pop.group.share.relative,H.group.share.relative,Q.group.share.relative,D.group.share.relative)
  colnames(relative.shares) <- c("prevalence.gen.pop", "prevalence.H", "prevalence.Q", "prevalence.D")

  return(relative.shares)
}


###############################################################################################################
###############################################################################################################
## PROJECTIONS BY RACE
###############################################################################################################
###############################################################################################################

# Pr.H.races <- H.risk.all.races
# Pr.Q.races <- Q.risk.all.races
# Pr.D.races <- D.risk.all.races
# nlevels <- length(Pr.H.races)
#
# Pr.pop <- race.pop
#
# # calculate relative shares in population, H, Q, D by race
# relative.shares.races <- calc.HQD.shares(Pr.pop=Pr.pop,Pr.H=Pr.H.races,Pr.Q=Pr.Q.races,Pr.D=Pr.D.races)
# rownames(relative.shares.races) <- race.order
#
# # process data for easy ggplot input
# relative.shares.races.melted <- melt(relative.shares.races, id=c("prevalence.gen.pop", "prevalence.H", "prevalence.Q", "prevalence.D"))
# relative.shares.races.melted$group <-relative.shares.races.melted$X1
# relative.shares.races.melted$stage <-relative.shares.races.melted$X2
# relative.shares.races.melted$values <-relative.shares.races.melted$value
# relative.shares.races.melted$X1 <- NULL
# relative.shares.races.melted$X2 <- NULL
# relative.shares.races.melted$value <- NULL
#
# relative.shares.races.melted <- relative.shares.races.melted %>% mutate(Race=factor(group,levels=c(race.order)))
#
# ###############################################################################################################
# ## Bar chart
#
# p.shares.races<-
#   relative.shares.races.melted %>%
#   mutate(stage = factor(stage, levels=c("prevalence.gen.pop", "prevalence.H", "prevalence.Q", "prevalence.D"))) %>%
#   ggplot( aes(x=stage, y=values,fill=Race)) +
# #  ggplot( aes(x=stage,y=values,fill=factor(group,levels=c(race.order))))+
#   geom_bar(position="stack", stat = 'identity')+
#   labs(title = "Illness Severity by Race/Ethnicity", x = "Stage", y = "Prevalence", legend="Race/Ethnicity") +
#   scale_x_discrete(labels = c("Population","Hospitalized","ICU","Dead"))
#
#
# ###############################################################################################################
# ## Trajectory plots
#
# ##trajectory-process-clean
#
# ## PROCESS MODEL PROJECTS DATA TO GET MEAN/MEDIAN  ############################################################################
# I.median <- traj.CI.out %>% select(c(date,state.name,median)) %>% filter(state.name==c("Idetectcum"))
# H.median <- traj.CI.out %>% select(c(date,state.name,median)) %>% filter(state.name==c("Htot"))
# Q.median <- traj.CI.out %>% select(c(date,state.name,median)) %>% filter(state.name==c("Q"))
# D.median <- traj.CI.out %>% select(c(date,state.name,median)) %>% filter(state.name==c("D"))
#
# I.median$I <- I.median$median
# I.median$median <- NULL
# H.median$H <- H.median$median
# H.median$median <- NULL
# H.median$state.name <- NULL
# Q.median$Q <- Q.median$median
# Q.median$median <- NULL
# D.median$D <- D.median$median
# D.median$median <- NULL
#
# IHQD.median <- cbind(I.median,H.median$H,Q.median$Q,D.median$D)
# IHQD.median$state.name = NULL
# colnames(IHQD.median) <- c("date","I","H","Q","D")
#
# ## FIX DATES ##################################################################
# IHQD.median$date <- as.Date(IHQD.median$date)
#
# ## ORGANIZE / CLEAN ##################################################################
# IHQD.median2 <- IHQD.median
# IHQD.median2$Illnesses <- IHQD.median2$I
# IHQD.median2$I <- NULL
# IHQD.median2$Hospitalizations <- IHQD.median2$H
# IHQD.median2$H <- NULL
# IHQD.median2$ICU <- IHQD.median2$Q
# IHQD.median2$Q <- NULL
# IHQD.median2$Deaths <- IHQD.median2$D
# IHQD.median2$D <- NULL
# IHQD.median2 <- melt(IHQD.median2,id = 'date')
# IHQD.median2$Stage <- IHQD.median2$variable
# IHQD.median2$variable <- NULL
#
#
# ##### trajectory-groupby.risk
#
# ## MERGE WITH COUNTS  ############################################################################
#
# str(IHQD.median2)
#
# #Add all the factor names so we can rename the factors in the dataframe to match the daily count
# TEST <- relative.shares.races.melted
# TEST$stage <- factor(TEST$stage, levels = c("prevalence.gen.pop", "prevalence.H", "prevalence.Q", "prevalence.D","Illnesses", "Hospitalizations", "ICU", "Deaths"  ))
# IHQD.median2$Stage <- factor(IHQD.median2$Stage, levels = c("prevalence.gen.pop", "prevalence.H", "prevalence.Q", "prevalence.D", "Illnesses", "Hospitalizations", "ICU", "Deaths"  ))
#
# #match the daily count naming
# TEST$stage[TEST$stage == "prevalence.gen.pop"] <- "Illnesses"
# TEST$stage[TEST$stage == "prevalence.H"] <- "Hospitalizations"
# TEST$stage[TEST$stage == "prevalence.Q"] <- "ICU"
# TEST$stage[TEST$stage == "prevalence.D"] <- "Deaths"
#
# #break down daily count by race shares
# count.races <- left_join(
#   IHQD.median2 %>% dplyr::rename(count=value),
#   TEST,
#   by = c("Stage" = "stage")
# ) %>%
#   dplyr::rename(prop=values) %>%
#   mutate(count_races=round(count*prop,3))
#
#
# ## TRAJECTORY PLOTS  ############################################################################
#
# ###trajectory-plotby.races
#
# #Population
#
# p.traj.race.I<-
#   ggplot(filter(count.races, Stage == "Illnesses"),
#          aes(x = date,
#              y = count_races,
#              fill = Race)) +
#   geom_area() +
#   #scale_fill_manual("legend", values = c("Risk 1" = "#ff0000", "Risk 2" = "#bf4000", "Risk 3" = "#7f7f00", "Risk 4" = "#40bf00", "Risk 5" = "#00ff00")) +
#   labs(title = "Projected Cumulative Illnesses by Race/Ethnicity (by population share)",
#        x = "Date",
#        y = "Cumulative Illnesses") +
#   scale_x_date(limits = as.Date(c("2020-03-01","2021-01-01")), date_breaks = "1 month" , date_labels = "%d-%b-%y") +
#   theme(axis.text.x = element_text(angle = 90),
#         strip.text.x = element_text(size = 12, face = "bold"))
#
# #Hospitalizations
#
# p.traj.race.H<-
#   ggplot(filter(count.races, Stage == "Hospitalizations"),
#          aes(x = date,
#              y = count_races,
#              fill = Race)) +
#   geom_area() +
#   labs(title = "Projected Hospitalizations by Race/Ethnicity for LA County",
#        x = "Date",
#        y = "Number in Hospital") +
#   scale_x_date(limits = as.Date(c("2020-03-01","2021-01-01")), date_breaks = "1 month" , date_labels = "%d-%b-%y") +
#   theme(axis.text.x = element_text(angle = 90),
#         strip.text.x = element_text(size = 12, face = "bold"))
#
# #ICU
#
# p.traj.race.Q<-
#   ggplot(filter(count.races, Stage == "ICU"),
#          aes(x = date,
#              y = count_races,
#              fill = Race)) +
#   geom_area() +
#   labs(title = "Projected ICU by Race/Ethnicity for LA County",
#        x = "Date",
#        y = "Number in ICU") +
#   scale_x_date(limits = as.Date(c("2020-03-01","2021-01-01")), date_breaks = "1 month" , date_labels = "%d-%b-%y") +
#   theme(axis.text.x = element_text(angle = 90),
#         strip.text.x = element_text(size = 12, face = "bold"))
#
# #Death
#
# p.traj.race.D<-
#   ggplot(filter(count.races, Stage == "Deaths"),
#          aes(x = date,
#              y = count_races,
#              fill = Race)) +
#   geom_area() +
#   labs(title = "Projected Deaths by Race/Ethnicity for LA County",
#        x = "Date",
#        y = "Number Deceased")+
#   scale_x_date(limits = as.Date(c("2020-03-01","2021-01-01")), date_breaks = "1 month" , date_labels = "%d-%b-%y") +
#   theme(axis.text.x = element_text(angle = 90),
#         strip.text.x = element_text(size = 12, face = "bold"))
#
#


#########################################################################################################
## PLOTS
#########################################################################################################

#p.shares.races

#p.traj.race.I + p.traj.race.H + p.traj.race.Q + p.traj.race.D




#########################################################################################################
#########################################################################################################
#########################################################################################################
#########################################################################################################
#########################################################################################################



